export const SHOW_FORM = "SHOW_FORM";
export const CLOSE_FORM = "CLOSE_FORM";
export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";
export const FETCH_LIST_PRODUCT_PAGINATION = "FETCH_LIST_PRODUCT_PAGINATION";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";

export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PODUCT_FROM_CART = "REMOVE_PODUCT_FROM_CART";
export const GET_CART_BY_USERID = "GET_CART_BY_USERID";
